"""
core/models/prompt_model.py
---------------------------
Pydantic v2 request/response models for the voice pipeline.
"""

from datetime import datetime, timezone
from typing import Literal
from pydantic import BaseModel, Field


# Supported languages
Language = Literal["en", "hi", "mr"]

# Supported prompt frameworks
Framework = Literal["CO-STAR", "ROSES", "RFGF", "Tree of Thoughts", "Chain of Thought"]

# Detected intent categories
Intent = Literal["writing", "coding", "business", "problem_solving", "quick"]


# ---------------------------------------------------------------------------
# Request
# ---------------------------------------------------------------------------

class VoiceProcessRequest(BaseModel):
    """
    Metadata sent alongside the audio file upload.
    The audio itself is passed as a multipart UploadFile — not in this model.
    """
    language: Language = Field(default="en", description="Language of the audio (en | hi | mr)")


# ---------------------------------------------------------------------------
# Response
# ---------------------------------------------------------------------------

class VoiceProcessResponse(BaseModel):
    """Full response returned after processing a voice recording."""
    id: str = Field(description="MongoDB ObjectId of the saved document")
    transcript: str = Field(description="Raw transcript from Deepgram")
    intent: Intent = Field(description="Detected intent category")
    framework: Framework = Field(description="Prompt framework used")
    generated_prompt: str = Field(description="Structured AI prompt generated by Groq")
    language: Language = Field(description="Audio language")
    processing_time_ms: int = Field(description="Total pipeline duration in milliseconds")
    created_at: datetime = Field(description="UTC timestamp of creation")


# ---------------------------------------------------------------------------
# History
# ---------------------------------------------------------------------------

class PromptHistoryItem(BaseModel):
    """A single saved prompt from MongoDB history."""
    id: str = Field(description="MongoDB ObjectId as string")
    transcript: str
    intent: Intent
    framework: Framework
    generated_prompt: str
    language: Language
    processing_time_ms: int
    created_at: datetime


class PromptHistoryList(BaseModel):
    """Paginated list of past prompts."""
    total: int
    items: list[PromptHistoryItem]
